version: "3.4"

services:
  alpaca-stock-trading-bot:
    build:
      context: .
      dockerfile: Dockerfile.stock
    container_name: alpaca-trading-bot-stock
    environment:
      - TZ=UTC
    restart: always

  alpaca-crypto-trading-bot:
    build:
      context: .
      dockerfile: Dockerfile.crypto
    container_name: alpaca-trading-bot-crypto
    environment:
      - TZ=UTC
    restart: always
